version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - USE_LOCAL_MODULUS=true
      - DEMO_MODE=true
      - JOB_BACKEND=background
      - LOG_LEVEL=INFO
    volumes:
      - ./uploads:/app/uploads
      - ./run_artifacts:/app/run_artifacts
      - ./assets:/app/assets
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Redis for Celery backend
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    profiles:
      - celery

  # Optional: Celery worker
  worker:
    build: .
    command: celery -A core.celery_app worker --loglevel=info
    environment:
      - USE_LOCAL_MODULUS=true
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    volumes:
      - ./uploads:/app/uploads
      - ./run_artifacts:/app/run_artifacts
      - ./assets:/app/assets
    depends_on:
      - redis
    restart: unless-stopped
    profiles:
      - celery

volumes:
  redis_data:
