import { useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Telescope, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { useExplorerMode } from "@/hooks/useFeatureFlag";
import { ExplorerResults } from "@/components/ExplorerResults";
import { ResearcherOnly } from "@/components/ResearcherOnly";
import { BaselineComparison } from "@/components/BaselineComparison";
import { sampleCandidates, Candidate } from "@/data/sampleCandidates";